topics:
  battery:
    voltage: "hoymiles/BATERIA_CASA_01/state/voltage"
    power: "hoymiles/BATERIA_CASA_01/state/power"
    soc: "hoymiles/BATERIA_CASA_01/state/soc"
    temperature: "hoymiles/BATERIA_CASA_01/state/temperature"
  grid:
    power_import: "hoymiles/BATERIA_CASA_01/state/grid_import"
    power_export: "hoymiles/BATERIA_CASA_01/state/grid_export"
  solar:
    power: "hoymiles/BATERIA_CASA_01/state/solar"
  load:
    power: "hoymiles/BATERIA_CASA_01/state/load"
